CREATE TABLE IF NOT EXISTS cursos (
    nome VARCHAR(30) NOT NULL UNIQUE,
    descricao TEXT,
    carga INT UNSIGNED,
    totaulas INT UNSIGNED,
    ano YEAR DEFAULT "2026"
) DEFAULT CHARSET = utf8;

ALTER TABLE cursos
ADD COLUMN id INT PRIMARY KEY AUTO_INCREMENT FIRST;

ALTER TABLE cursos
CHANGE COLUMN id idcurso INT;

ALTER TABLE cursos
MODIFY COLUMN idcurso INT AUTO_INCREMENT;

DESC cursos;